name: Actions complete

on: 

  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  
  workflow_dispatch:

jobs:
      
  bb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: cat a.py
